### ISSUE TITLE
貌似Crypto有破坏性更新

### ISSUE THREAD

**Issue by frozonTzh** [fkxxyz/ssfconv#16]
### 报错日志

Traceback (most recent call last):
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/./ssfconv", line 1211, in <module>
    exit(main(args))
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/./ssfconv", line 1170, in main
    extractSsf(args.src, dest_dir)
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/./ssfconv", line 35, in extractSsf
    ssfAES = AES.new(aesKey, AES.MODE_CBC, iv)
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/venv/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/venv/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/run/media/frozon/manjaro home/frozon/下载/rime/ssfconv/venv/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

#### python 版本
Python 3.10.5
  #### pip list
numpy      1.22.4
Pillow     9.1.1
pip        22.0.4
pycrypto   2.6.1
setuptools 58.1.0

**Comment by frozonTzh** [comment]
更换了Python 3.9.13问题就不存在了

**Comment by ydrk12** [comment]
我这边也是这个问题，使用的是python3.10，这应该是个值得注意的修复
