### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by zetako** [fkxxyz/ssfconv#5]
转换fcitx5皮肤的时候出现错误
```shell
Traceback (most recent call last):
  File "/usr/bin/ssfconv", line 1203, in <module>
    exit(main(args))
  File "/usr/bin/ssfconv", line 1175, in main
    result = ssr2fcitx5(skin_dir)
  File "/usr/bin/ssfconv", line 819, in ssr2fcitx5
    back_color = findBackgroundColor()
  File "/usr/bin/ssfconv", line 801, in findBackgroundColor
    return getImageAvg(skin_dir + os.sep + image_name,
  File "/usr/bin/ssfconv", line 118, in getImageAvg
    if a[y][x][3] > 0:
IndexError: index 3 is out of bounds for axis 0 with size 3
```
转换使用的文件：
[1.zip](https://github.com/fkxxyz/ssfconv/files/5213852/default.zip)

**Comment by fkxxyz** [comment]
感谢，由于没有考虑到搜狗皮肤用的图片可能是 24 位深度缘故导致，只考虑了 32 位，现在将改进。
